import { DownloadSimple, PencilSimple, Plus, SlidersHorizontal, Trash, UploadSimple } from '@phosphor-icons/react';
import { useState, type ChangeEvent } from 'react';
import { Dialog } from '../../../components/Dialog';
import { createDefaultPreset, exportPreset, exportToJson, importPreset, type ChatPreset } from '../../../sillytavern';
import { useTavern } from '../runtime/useTavern';
import { PresetEditorDialog } from './PresetEditorDialog';

export function PresetManager() {
  const runtime = useTavern();
  const [editing, setEditing] = useState<ChatPreset | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ChatPreset | null>(null);
  const [error, setError] = useState('');
  const activate = async (preset: ChatPreset) => { if (runtime.settings) await runtime.updateSettings({ ...runtime.settings, activePresetId: preset.id }); };
  const create = () => { const now = Date.now(); setEditing({ ...createDefaultPreset(), id: crypto.randomUUID(), name: `新预设 ${runtime.presets.length + 1}`, createdAt: now, updatedAt: now }); };
  const importFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { const imported = importPreset(JSON.parse(await file.text()) as Record<string, unknown>); const now = Date.now(); const preset = { ...imported, id: crypto.randomUUID(), createdAt: now, updatedAt: now }; await runtime.upsertPreset(preset); await activate(preset); setError(''); } catch { setError('预设导入失败：JSON 文件无法解析。'); } };
  return <section id="tavern-panel-presets" className="tavern-panel-stack" role="tabpanel" aria-labelledby="tavern-tab-presets"><header className="tavern-section-heading"><div><span className="panel-code">SAMPLING & PROMPTS / OPENAI</span><h3>生成预设</h3><p>配置模型采样、上下文预算与提示词块。顺序按钮同时支持键盘操作与明确的禁用状态。</p></div><div className="tavern-toolbar"><label className="terminal-button" htmlFor="preset-import-input"><UploadSimple size={16} aria-hidden />导入预设</label><input id="preset-import-input" className="visually-hidden" type="file" accept=".json,application/json" aria-label="导入 SillyTavern 预设" onChange={(event) => void importFile(event)} /><button id="preset-create-button" className="terminal-button is-primary" type="button" onClick={create}><Plus size={16} aria-hidden />新建预设</button></div></header>{error ? <p role="alert" className="tavern-form-error">{error}</p> : null}<div className="tavern-asset-grid">{runtime.presets.map((preset) => { const active = runtime.activePreset?.id === preset.id; return <article key={preset.id} className={active ? 'is-active' : ''} aria-label={`生成预设 ${preset.name}`}><div className="tavern-asset-icon"><SlidersHorizontal size={24} aria-hidden /></div><div className="tavern-asset-copy"><strong>{preset.name}</strong><p>{preset.description || '未填写预设说明'}</p><span>T {String(preset.settings.temp_openai ?? '—')} · CTX {String(preset.settings.openai_max_context ?? '—')}</span></div><div className="tavern-asset-actions">{active ? <b>当前预设</b> : <button id={`preset-activate-${preset.id}`} type="button" onClick={() => void activate(preset)}>设为当前</button>}<button id={`preset-edit-${preset.id}`} type="button" aria-label={`编辑预设 ${preset.name}`} onClick={() => setEditing(preset)}><PencilSimple size={16} aria-hidden /></button><button id={`preset-export-${preset.id}`} type="button" aria-label={`导出预设 ${preset.name}`} onClick={() => exportToJson(exportPreset(preset), `${safeName(preset.name)}.json`)}><DownloadSimple size={16} aria-hidden /></button><button id={`preset-delete-${preset.id}`} type="button" aria-label={`删除预设 ${preset.name}`} onClick={() => setDeleteTarget(preset)}><Trash size={16} aria-hidden /></button></div></article>; })}</div><PresetEditorDialog preset={editing} open={Boolean(editing)} onClose={() => setEditing(null)} onSave={async (preset) => { await runtime.upsertPreset(preset); }} /><Dialog id="preset-delete-dialog" title="确认删除生成预设" open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} danger footer={<><button className="terminal-button" type="button" onClick={() => setDeleteTarget(null)}>取消</button><button className="terminal-button is-danger" type="button" onClick={() => { if (deleteTarget) void runtime.removePreset(deleteTarget.id); setDeleteTarget(null); }}>确认删除</button></>}><p>删除预设不会修改已生成内容；引用该预设的会话将回退至当前预设。</p></Dialog></section>;
}
function safeName(name: string) { return name.replace(/[\\/:*?"<>|]/g, '_'); }
